In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pandas import ExcelWriter
from pandas import ExcelFile

%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel('original.xlsx')

In [3]:
df.head()

churn  age rent_or_own  trivia_played  trivia_shared_results  \
0      1   22         NaN              0                      0   
1      1   25           R              0                      0   
2      1   32         NaN              0                      0   
3      1   26         NaN              0                      0   
4      1   28           R              0                      0   

   trivia_view_unlocked  trivia_view_results  cards_share  cards_viewed  \
0                     0                    0            0            48   
1                     5                    0            0             5   
2                     0                    0            0            49   
3                   169                    0            0           184   
4                    11                    0            0            65   

   cards_helpful  ...    payfreq  loan_pending  withdrawn_application  \
0              0  ...     Weekly             0                      0   
1              0  ...     Weekly             0                      0   
2              0  ...  Bi-Weekly             0                      0   
3              0  ...         na             0                      0   
4              0  ...         na             0                      0   

   paid_off_loan  did_not_accept_funding  zodiac_sign  un_linked_account  \
0              0                       0       Taurus                  0   
1              0                       0       Gemini                  0   
2              0                       0        Virgo                  0   
3              0                       0          Leo                  0   
4              0                       0       Cancer                  0   

  re_linked_account  cash_back_engagement  has_referred  
0                 0                  0.57             0  
1                 0                  0.07             0  
2                 0                  0.60             1  
3                 0                  1.77             1  
4                 0                  1.23             1  

[5 rows x 27 columns]

In [4]:
df.rent_or_own.mode()

0    R
dtype: object

In [5]:
df.rent_or_own.fillna("R", inplace = True)

In [6]:
df.head()

churn  age rent_or_own  trivia_played  trivia_shared_results  \
0      1   22           R              0                      0   
1      1   25           R              0                      0   
2      1   32           R              0                      0   
3      1   26           R              0                      0   
4      1   28           R              0                      0   

   trivia_view_unlocked  trivia_view_results  cards_share  cards_viewed  \
0                     0                    0            0            48   
1                     5                    0            0             5   
2                     0                    0            0            49   
3                   169                    0            0           184   
4                    11                    0            0            65   

   cards_helpful  ...    payfreq  loan_pending  withdrawn_application  \
0              0  ...     Weekly             0                      0   
1              0  ...     Weekly             0                      0   
2              0  ...  Bi-Weekly             0                      0   
3              0  ...         na             0                      0   
4              0  ...         na             0                      0   

   paid_off_loan  did_not_accept_funding  zodiac_sign  un_linked_account  \
0              0                       0       Taurus                  0   
1              0                       0       Gemini                  0   
2              0                       0        Virgo                  0   
3              0                       0          Leo                  0   
4              0                       0       Cancer                  0   

  re_linked_account  cash_back_engagement  has_referred  
0                 0                  0.57             0  
1                 0                  0.07             0  
2                 0                  0.60             1  
3                 0                  1.77             1  
4                 0                  1.23             1  

[5 rows x 27 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
df.rent_or_own = le.fit_transform(df.rent_or_own)

In [9]:
df.payfreq = le.fit_transform(df.payfreq)
df.zodiac_sign = le.fit_transform(df.zodiac_sign)

In [10]:
df.head()

churn  age  rent_or_own  trivia_played  trivia_shared_results  \
0      1   22            1              0                      0   
1      1   25            1              0                      0   
2      1   32            1              0                      0   
3      1   26            1              0                      0   
4      1   28            1              0                      0   

   trivia_view_unlocked  trivia_view_results  cards_share  cards_viewed  \
0                     0                    0            0            48   
1                     5                    0            0             5   
2                     0                    0            0            49   
3                   169                    0            0           184   
4                    11                    0            0            65   

   cards_helpful  ...  payfreq  loan_pending  withdrawn_application  \
0              0  ...        3             0                      0   
1              0  ...        3             0                      0   
2              0  ...        0             0                      0   
3              0  ...        4             0                      0   
4              0  ...        4             0                      0   

   paid_off_loan  did_not_accept_funding  zodiac_sign  un_linked_account  \
0              0                       0           10                  0   
1              0                       0            4                  0   
2              0                       0           11                  0   
3              0                       0            5                  0   
4              0                       0            2                  0   

   re_linked_account  cash_back_engagement  has_referred  
0                  0                  0.57             0  
1                  0                  0.07             0  
2                  0                  0.60             1  
3                  0                  1.77             1  
4                  0                  1.23             1  

[5 rows x 27 columns]

In [11]:
df.age.corr(df.churn)

-0.060525194864038775

In [12]:
a = df.columns

In [13]:
a

Index(['churn', 'age', 'rent_or_own', 'trivia_played', 'trivia_shared_results',
       'trivia_view_unlocked', 'trivia_view_results', 'cards_share',
       'cards_viewed', 'cards_helpful', 'cards_not_helpful', 'cards_clicked',
       'has_used_mobile', 'has_used_web', 'used_android', 'used_ios',
       'more_than_one_mobile_device', 'payfreq', 'loan_pending',
       'withdrawn_application', 'paid_off_loan', 'did_not_accept_funding',
       'zodiac_sign', 'un_linked_account', 're_linked_account',
       'cash_back_engagement', 'has_referred'],
      dtype='object')

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [15]:
X = df.drop(['churn'],axis=1)
Y = df.churn

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 25)

In [17]:
rf.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [18]:
Y_pred = rf.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [20]:
confusion_matrix(Y_test,Y_pred)

array([[4850,  815],
       [1579, 2372]], dtype=int64)

In [21]:
accuracy_score(Y_test,Y_pred)

0.7510399334442596

In [22]:
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
xgb_nst = XGBClassifier()

In [23]:
params={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

In [24]:
random_search=RandomizedSearchCV(xgb_nst,param_distributions=params,n_iter=5,scoring='roc_auc',n_jobs=-1,cv=5,verbose=3)

In [25]:
random_search.fit(X_train,Y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  19 out of  25 | elapsed:   10.3s remaining:    3.2s
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:   11.9s finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objective='binary:logistic',
                                           random_state=0, reg_alpha=0,
                                           reg_lambda=1, sc...
                                           verbosity=1),
                   iid='deprecated', n_iter=5, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0

In [26]:
random_search.best_params_

{'min_child_weight': 1,
 'max_depth': 5,
 'learning_rate': 0.05,
 'gamma': 0.4,
 'colsample_bytree': 0.5}

In [27]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(rf,X_train,Y_train,cv=15)

In [28]:
score

array([0.74152047, 0.74269006, 0.74424951, 0.73127925, 0.73088924,
       0.73673947, 0.75      , 0.72815913, 0.74804992, 0.74063963,
       0.73790952, 0.75351014, 0.74414977, 0.7550702 , 0.7301092 ])

In [29]:
score.max()

0.7550702028081123

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [31]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [32]:
X_train

array([[-0.11348653,  0.28921954, -0.3661554 , ..., -0.13733327,
         0.74786676, -0.67935762],
       [-0.61962416, -3.45758108, -0.3661554 , ..., -0.13733327,
         1.148959  , -0.67935762],
       [ 0.79756122, -3.45758108, -0.25491799, ..., -0.13733327,
        -1.21748522,  1.47197879],
       ...,
       [-0.61962416,  0.28921954, -0.3661554 , ..., -0.13733327,
        -0.99019962,  1.47197879],
       [-0.11348653,  0.28921954, -0.3661554 , ..., -0.13733327,
        -1.21748522, -0.67935762],
       [-0.72085169,  0.28921954, -0.3661554 , ..., -0.13733327,
         0.88156417,  1.47197879]])

In [33]:
rf1 = RandomForestClassifier()

In [34]:
rf1.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [35]:
Y_pred1 = rf1.predict(X_test)

In [36]:
confusion_matrix(Y_test,Y_pred1)

array([[4843,  822],
       [1636, 2315]], dtype=int64)

In [38]:
accuracy_score(Y_pred1,Y_test)

0.7443843594009983